### ISSUE TITLE
Device: Version mismatch. Recieved packet of version 55 but expected version 0

### ISSUE THREAD

**Issue by arthurzenika** [USU-Security/oip#9]
On the server side I have oipd from packages

```
# apt-cache policy oipd
oipd:
  Installed: 0.05-eldraco-1~security71+3
  Candidate: 0.05-eldraco-1~security71+3
  Version table:
 *** 0.05-eldraco-1~security71+3 0
        100 http://mirror.usu.edu/usu-security/ wheezy-security-stable/main amd64 Packages
        100 /var/lib/dpkg/status
```
on the client side, I'm using a compiled version from git (0.06 ?).  It doesn't display anything and on the server side I get : 

```
# oipd
Welcome
Device: Version mismatch. Recieved packet of version 55 but expected version 0
Unknown message type: 109
Version mismatch. Recieved packet of version 199 but expected version 0
Unknown message type: 38
```

**Comment by ekoyle** [comment]
I suspect they were compiled with different ./configure options, some of
which affect the length of the summary packets.

On Nov 24, 2016 7:19 AM, "Arthur Lutz" <notifications@github.com> wrote:

On the server side I have oipd from packages

# apt-cache policy oipd
oipd:
  Installed: 0.05-eldraco-1~security71+3
  Candidate: 0.05-eldraco-1~security71+3
  Version table:
 *** 0.05-eldraco-1~security71+3 0
        100 http://mirror.usu.edu/usu-security/
wheezy-security-stable/main amd64 Packages
        100 /var/lib/dpkg/status

on the client side, I'm using a compiled version from git (0.06 ?). It
doesn't display anything and on the server side I get :

# oipd
Welcome
Device: Version mismatch. Recieved packet of version 55 but expected version 0
Unknown message type: 109
Version mismatch. Recieved packet of version 199 but expected version 0
Unknown message type: 38

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/USU-Security/oip/issues/9>, or mute the thread

**Comment by arthurlogilab** [comment]
@ekoyle thanks for your answer. Am using default ./configure (no flags), can you be more precise with which flags I should play with to try to get it to work ? 

Do you know where the flags used for building the debian pkg can be found ?

**Comment by ekoyle** [comment]
It looks like the debian package doesn't do anything special with the ./configure.  It could also be something that changed between the two versions, although I don't remember making any protocol changes.

**Comment by ekoyle** [comment]
@arthurlogilab: also, this can happen when the shared secret doesn't match between the server and client
